# Generated by Django 4.1 on 2022-11-21 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0002_alter_challenges_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 26, 52, 687087)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 12, 26, 52, 687048)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 26, 52, 677449)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 12, 26, 52, 677401)),
        ),
    ]
