# Generated by Django 4.1 on 2023-03-23 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0003_alter_challenges_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 9, 20, 23, 300374)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 9, 20, 23, 300361)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 9, 20, 23, 297280)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 9, 20, 23, 297261)),
        ),
    ]
