# Generated by Django 4.1 on 2023-04-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[['All', 'All'], ['Profit and Loss', 'Profit and Loss'], ['Time and Work', 'Time and Work'], ['Time and Distance', 'Time and Distance'], ['Number System', 'Number System'], ['Average', 'Average'], ['Percentage', 'Percentage'], ['Ratio and Proportion', 'Ratio and Proportion'], ['Mensuration', 'Mensuration'], ['Simple Interest', 'Simple Interest'], ['Compound Interest', 'Compound Interest'], ['Algebra', 'Algebra'], ['Geometry', 'Geometry'], ['Trigonometry', 'Trigonometry'], ['Data Interpretation', 'Data Interpretation'], ['Miscellaneous', 'Miscellaneous']], default='All', max_length=100)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, verbose_name='Choice')),
                ('position', models.IntegerField(verbose_name='position')),
                ('answer_position', models.IntegerField(verbose_name='answer_position')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='corival.apptitude')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('question', 'position'), ('question', 'choice')},
            },
        ),
    ]
