# Generated by Django 4.0 on 2022-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
