# Generated by Django 4.1 on 2023-04-01 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0002_apptitude_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptitude',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
