# Generated by Django 4.1 on 2023-04-03 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0002_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptitude',
            name='difficulty',
            field=models.IntegerField(choices=[[1, 'Easy'], [2, 'Medium'], [3, 'Hard']], default=1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(choices=[[1, 'Easy'], [2, 'Medium'], [3, 'Hard']], default=1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 19, 15, 20, 718552)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='difficulty',
            field=models.IntegerField(choices=[[1, 'Easy'], [2, 'Medium'], [3, 'Hard']], default=1),
        ),
        migrations.AlterField(
            model_name='practice',
            name='difficulty',
            field=models.IntegerField(choices=[[1, 'Easy'], [2, 'Medium'], [3, 'Hard']], default=1),
        ),
    ]
