# Generated by Django 4.0 on 2022-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
    ]
