# Generated by Django 4.1 on 2023-04-03 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0003_alter_apptitude_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 19, 15, 25, 441171)),
        ),
    ]
