# Generated by Django 4.1 on 2023-04-01 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0003_apptitude_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[['All', 'All'], ['Profit and Loss', 'Profit and Loss'], ['Time and Work', 'Time and Work'], ['Time and Distance', 'Time and Distance'], ['Number System', 'Number System'], ['Average', 'Average'], ['Percentage', 'Percentage'], ['Ratio and Proportion', 'Ratio and Proportion'], ['Mensuration', 'Mensuration'], ['Simple Interest', 'Simple Interest'], ['Compound Interest', 'Compound Interest'], ['Algebra', 'Algebra'], ['Geometry', 'Geometry'], ['Trigonometry', 'Trigonometry'], ['Data Interpretation', 'Data Interpretation'], ['Miscellaneous', 'Miscellaneous']], default='All', max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='corival.apptitude')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timm_took', models.TimeField()),
                ('answer', models.BooleanField(default=False)),
                ('apptitude', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to='corival.apptitude')),
                ('practice', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='corival.practice')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
