# Generated by Django 4.1 on 2023-04-03 13:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0004_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 19, 25, 25, 884807)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='answer_position'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='position'),
        ),
    ]
