# Generated by Django 4.1 on 2023-04-01 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0005_challenge_contest_contestsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 15, 7, 27, 186229)),
        ),
    ]
