# Generated by Django 4.1 on 2023-04-16 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0006_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestleaderboard',
            options={'ordering': ['-score', 'time_taken']},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 18, 55, 59, 993243)),
        ),
        migrations.AlterField(
            model_name='challengeleaderboard',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='practice',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
