# Generated by Django 4.0 on 2022-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0006_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='no_of_questions',
            field=models.IntegerField(default=20),
        ),
    ]
