# Generated by Django 4.1 on 2023-04-03 14:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0006_alter_challenge_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer_position',
        ),
        migrations.AddField(
            model_name='apptitude',
            name='answer_position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='answer_position'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 20, 2, 53, 958600)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=100, verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='position'),
        ),
    ]
