# Generated by Django 4.1 on 2023-04-03 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0007_remove_choice_answer_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 20, 2, 55, 597249)),
        ),
    ]
