# Generated by Django 4.1 on 2023-04-16 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0007_alter_contestleaderboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 18, 56, 2, 92467)),
        ),
    ]
