# Generated by Django 4.0 on 2022-05-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0007_competition_no_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message_url',
            field=models.TextField(),
        ),
    ]
