# Generated by Django 4.1 on 2023-04-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0008_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptitude',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 20, 11, 44, 506320)),
        ),
    ]
