# Generated by Django 4.0 on 2022-06-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0008_alter_notifications_message_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_practice',
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('no_of_questions', models.IntegerField(default=20)),
                ('score', models.IntegerField(blank=True)),
                ('questions', models.ManyToManyField(related_name='practicequestions', to='corival.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corival.user')),
            ],
        ),
    ]
