# Generated by Django 4.0 on 2022-06-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0009_remove_competition_is_practice_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
