# Generated by Django 4.0 on 2022-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0010_alter_practice_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='alerType',
            field=models.CharField(choices=[('CH', 'Challenge'), ('COMP', 'Competition'), ('USR', 'User'), ('PRC', 'Practice')], default=None, max_length=100, null=True),
        ),
    ]
