# Generated by Django 4.1 on 2023-04-01 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0012_alter_challenge_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, default='Hi there! I am using Corival'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 21, 31, 12, 398792)),
        ),
    ]
