# Generated by Django 4.1 on 2023-05-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0013_alter_challenge_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 18, 52, 38, 256391)),
        ),
    ]
