# Generated by Django 4.1 on 2023-04-01 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0013_remove_user_description_candidate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 21, 31, 17, 252445)),
        ),
    ]
