# Generated by Django 4.0 on 2022-06-22 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0014_alter_competition_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 13, 23, 29, 776745)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='corival.Questions'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 13, 23, 29, 776745)),
        ),
    ]
