# Generated by Django 4.0 on 2022-06-23 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0019_compresponse_start_time_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 23, 11, 58, 988704)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 23, 11, 58, 988704)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profilepic'),
        ),
    ]
