# Generated by Django 4.0 on 2022-06-24 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0020_practice_title_alter_competition_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_challenge',
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 15, 30, 2, 800200)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 30, 2, 800200)),
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 30, 2, 800200))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 15, 30, 2, 800200))),
                ('duration', models.DurationField()),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('opponent_score', models.IntegerField(blank=True, null=True)),
                ('no_of_questions', models.IntegerField(default=20)),
                ('finished', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='corival.user')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chllengee', to='corival.user')),
                ('questions', models.ManyToManyField(blank=True, related_name='challenge_questions', to='corival.Questions')),
            ],
        ),
    ]
