# Generated by Django 4.1 on 2023-04-07 15:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0020_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesubmission',
            name='user_choice',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 21, 24, 4, 477404)),
        ),
    ]
