# Generated by Django 4.0 on 2022-06-30 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0021_remove_competition_is_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 10, 9, 37, 730703)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 10, 9, 37, 730703)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 10, 9, 37, 713664)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 10, 9, 37, 713664)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='files/profile', verbose_name='profilepic'),
        ),
    ]
