# Generated by Django 4.1 on 2023-04-07 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0022_alter_challenge_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicesubmission',
            old_name='timm_took',
            new_name='time_taken',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 21, 41, 51, 356227)),
        ),
    ]
