# Generated by Django 4.0 on 2022-07-30 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0023_alter_challenges_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 11, 31, 610301)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 20, 11, 31, 610301)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 20, 11, 31, 610301)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 20, 11, 31, 610301)),
        ),
        migrations.AlterField(
            model_name='compresponse',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='corival/files/profile', verbose_name='profilepic'),
        ),
    ]
