# Generated by Django 4.0 on 2022-07-30 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0024_alter_challenges_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 23, 56, 33, 265423)),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 23, 56, 33, 265423)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 23, 56, 33, 249804)),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 23, 56, 33, 249804)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Hello there! Just started Competiting.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1500, null=True),
        ),
    ]
