# Generated by Django 4.1 on 2023-04-07 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0024_alter_challenge_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 21, 54, 33, 895977)),
        ),
        migrations.AlterField(
            model_name='practicesubmission',
            name='time_taken',
            field=models.DurationField(),
        ),
    ]
