# Generated by Django 4.1 on 2023-04-07 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corival', '0025_alter_challenge_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 21, 54, 36, 509069)),
        ),
    ]
